package io.github.bluegroundltd.schemaregistry

import com.fasterxml.jackson.module.kotlin.KotlinModule
import io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer

/**
 * Enhances the [KafkaJsonSchemaSerializer] with the Jackson Kotlin module
 *
 * When `auto.register.schemas: true` is used for a Kafka producer the serializer will generate a schema based on the
 * Kotlin POJOs. The object mapper used under the hood needs the Kotlin module to populate the `required` fields of the
 * schema. Otherwise, only primitive types are seen as non-nullable.
 *
 * Using this serializer ensures that the auto registered schema will be the same as the one generated by our gradle
 * plugin.
 */
class KotlinKafkaJsonSchemaSerializer<T> : KafkaJsonSchemaSerializer<T>() {
  override fun configure(config: Map<String?, *>, isKey: Boolean) {
    super.configure(config, isKey)
    objectMapper.registerModule(KotlinModule.Builder().build())
  }
}
